services:
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service-container
    ports:
      - "8762:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 4

  config-service:
    build: ./config-service
    container_name: config-service-container
    ports:
      - '9999:9999'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service-container:8761/eureka
    depends_on:
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4

  customer-service:
    build: ./customer-service
    container_name: customer-service-container
    ports:
      - '8085:8085'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service-container:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service-container:9999
    depends_on:
      config-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8085/actuator/health" ]
      interval: 10s
      retries: 4

  account-service:
    build: ./account-service
    container_name: account-service-container
    ports:
      - '8086:8086'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service-container:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service-container:9999
    depends_on:
      customer-service:
        condition: service_healthy

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service-container
    ports:
      - '8888:8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service-container:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service-container:9999
    depends_on:
      config-service:
        condition: service_healthy

  ebank-front-service:
    build: ./angular-front-end
    container_name: ebank-front-service-container
    ports:
      - '80:80'
    expose:
      - '80'



