spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
#spring:
#  cloud:
#    gateway:
#      server:
#        webflux:
#          routes:
#            - id: r1
#              uri: http://localhost:8085/
#              predicates:
#                - Path=/customers/**
#
#            - id: r2
#              uri: http://localhost:8086/
#              predicates:
#                - Path=/accounts/**