spring.application.name=config-service
server.port=9999
#spring.cloud.config.server.git.uri=file://G:/amir/micro_services/yousfi/ms-ebank/config-repo
spring.cloud.config.server.git.uri=https://github.com/zorganimed/ebank-config-repo
